# Generated by Django 2.2.1 on 2019-05-28 06:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='主键')),
                ('title', models.CharField(max_length=40, verbose_name='标题')),
                ('intr', models.CharField(max_length=256, verbose_name='简介')),
                ('content', models.CharField(max_length=1024, verbose_name='内容')),
                ('username', models.CharField(max_length=40, verbose_name='用户名')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发布时间')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='主键')),
                ('name', models.CharField(max_length=40, verbose_name='用户名')),
                ('password', models.CharField(max_length=40, verbose_name='密码')),
                ('userType', models.CharField(default='1', max_length=2, verbose_name='分类')),
            ],
        ),
    ]
